### ISSUE TITLE
focus on a node

### ISSUE THREAD

**Issue by Vanderscycle** [anvaka/ngraph.pixel#18]
Hi,

Thank you for the time and effort you have put into this library. My question is simple, is there a way to focus on a specific node? for example call node 1234 and make it focus around said node.

Edit: how can I access the ThreeJs object used by graph.pixel?

Thanks,

**Comment by brienna** [comment]
I've got the same question, and just dropped by to see if there had been any additional insight into how to do this. Off the top off my head I know that you can do that in anvaka's pm package

**Comment by Vanderscycle** [comment]
I ended up moving to [this](https://github.com/vasturiano/3d-force-graph) which builds on top of the excellent ngraph lib.

**Comment by brienna** [comment]
Thanks @Vanderscycle!
