### ISSUE TITLE
npm start seems to be broken do to a path issue

### ISSUE THREAD

**Issue by calvertj** [anvaka/ngraph.pixel#2]
the tooltip.js has a path which I believe to be incorrect, at least when just dealing with ngraph.pixel

**Comment by anvaka** [comment]
Should be fixed by https://github.com/anvaka/ngraph.pixel/commit/cd1cfc3926c21e60813b59634dd942a4622b861d and released in `v0.1.13`

**Comment by anvaka** [comment]
Thank you!
