### ISSUE TITLE
Setting position / pinning does not work

### ISSUE THREAD

**Issue by cassinius** [anvaka/ngraph.pixel#7]
Hello,
I am using ngraph.pixel with pixel.layout in a 3D setting - but whatever I do, I am not able to render a graph with constant coordinates (without forces acting on the position). I've tried to setNodePosition to no avail, as well as setting all physical forces to zero - with no effect. The only way to manipulate coordinates is to call renderer.getNode(node_id).position.[x|y|z] = [someCoord] - which changes the coordinate, but immediately the physics system pulls the node back into it's computed position. Is there any way to deactivate the physics system altogether? (I've also tried to set the simulator to undefined, but that didn't work either). I would appreciate any help, my use case calls for a constant 3D layout.. best, Bernd

**Comment by anvaka** [comment]
Hi Bernd,

I wonder if this would work: https://github.com/anvaka/pixel.static ?

**Comment by cassinius** [comment]
That was exactly what I was looking for... didn't see that module ;) thx!

**Comment by anvaka** [comment]
Awesome! The module was obscured, and I wasn't sure if its API is sufficient - I had no use case for it, so it was lying hidden. Let me know if you run into any issues with it!
