### ISSUE TITLE
Node hover not working completely

### ISSUE THREAD

**Issue by noopurj** [anvaka/ngraph.pixel#8]
Hello,

I have been using ngraph.pixel to visualize graphs and its working properly except for the tooltip that appears on node hover. Especially when there are overlapping nodes, hovering over just a single node shows different node ids while hovering over different parts of the same node. Some nodes do not show the tooltip even when I hover the mouse pointer over them, it only shows the tooltip when the mouse is outside the node's border, like so -

![capture](https://cloud.githubusercontent.com/assets/9455527/13472000/06565d20-e081-11e5-8ad6-29d8d7362f95.png)

This happens in the demo given in the repo too (https://github.com/anvaka/ngraph.pixel/tree/master/demo/config).
<img width="1274" alt="screen shot 2016-03-01 at 2 41 57 pm" src="https://cloud.githubusercontent.com/assets/9455527/13472039/294d40c8-e081-11e5-8e4e-9b09fa3af6b9.png">

Apparently, the renderer.on('nodehover, function(node){….} doesn't work for the nodes that don't show the tooltip, as I am using this function to display other properties of a node on a separate division with a fixed position. So neither the tooltip nor the other info is visible via renderer.on('nodehover...

To help debugging, here's a fiddle of a sample graph for which the hover function doesn't work properly.

[https://jsfiddle.net/noopur/b94wvLx2/](url)

**Comment by anvaka** [comment]
I think I found a reason for that behavior and fixed it - please grab the latest version and let me know;

By the way in the jsfiddle link your provided has a small typo in CSS. Change `postion: absolute;` to `        position: absolute;`

**Comment by noopurj** [comment]
Yes, it is much more accurate now, thank you. 

Thank you so much for pointing out my typo too, I corrected it.
